[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force previews and www → apex
[[redirects]]
  from = "/*"
  to = "https://tradeautobill.com/:splat"
  status = 301
  force = true
  conditions = { Host = [
    "incomparable-tulumba-7feb45.netlify.app",
    "main--incomparable-tulumba-7feb45.netlify.app",
    "www.tradeautobill.com"
  ] }

# Back-compat for old endpoint
[[redirects]]
  from = "/api/billing/portal"
  to = "/api/billing-portal"
  status = 308
  force = true
